version: "3"

services:
    client:
        restart: on-failure
        stdin_open: true
        build: .
        container_name: client-web2
        volumes:
            - c:\_wp\web2-2020\client
        ports:
            - 9000:5000
        environment:
            - API_URL=http://localhost:4000
            - NODE_ENV=production
